### ISSUE TITLE
Getting an error for find function 

### ISSUE THREAD

**Issue by vuk** [yangqi/Htmldom#11]
When I execute an example from home page here, I get this error 

```
Call to a member function find() on a non-object
```

Strange thing is that when I execute this on my localhost, it works as expected, but on remote server it fails. With this error. 

Also, when i 

```
var_dump($html)
```

I can see that it is an object. So any ideas?

**Comment by fikoborquez** [comment]
Which are the php versions of localhost and remote server?

I suspect that the remote server has not installed a supported version of php

**Comment by fowlerwill** [comment]
Same error - 
`>>> print phpversion();
5.5.9-1ubuntu4.14`

`PHP Fatal error:  Call to a member function find() on a non-object in .../vendor/yangqi/htmldom/src/Yangqi/Htmldom/Htmldom.php on line 272
`

and the call being made:
```
$this->html = new \Htmldom('http://www.calgarysportsclub.com/');
$this->menu = $this->html->find('#block-menu-block-1 > div > ul li a');
```

**Comment by salvisb** [comment]
The same here when using php 5.5.12. Everthing were fine with php 5.4.

**Comment by yangqi** [comment]
I came across this bug report, might be helpful. Need to update MAX_FILE_SIZE in Htmldom.php file.

https://sourceforge.net/p/simplehtmldom/bugs/137/

**Comment by salvisb** [comment]
@yangqi it doesn't help. Looks like something is missing in PHP settings. But can't figure out what exacly.

**Comment by bigenius** [comment]
This is from the FAQ on the simplehtmldom page:

> Q: On my local server everything works fine, but when I put it on my esternal server it doesn't work. 
> A: The "file_get_dom" function is a wrapper of "file_get_contents" function,  you must set "allow_url_fopen" as TRUE in "php.ini" to allow accessing files via HTTP or FTP. However, some hosting venders disabled PHP's "allow_url_fopen" flag for security issues... PHP provides excellent support for "curl" library to do the same job, Use curl to get the page, then call "str_get_dom" to create DOM object. 
> 

Example: 
 ```

$curl = curl_init(); 
curl_setopt($curl, CURLOPT_URL, 'http://????????');  
curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);  
curl_setopt($curl, CURLOPT_CONNECTTIMEOUT, 10);  
$str = curl_exec($curl);  
curl_close($curl);  
 
$html= str_get_html($str); 
```

Could this be your problem?

**Comment by vijay-dhokrat** [comment]
Hi All,
Can anyone please help me out here
I getting one Exception, please tell me how can I handle this one
Symfony\Component\Debug\Exception\FatalErrorException’ with message ‘Call to a member function find()
