### ISSUE TITLE
not compatible to php 7.3!

### ISSUE THREAD

**Issue by dereuromark** [yangqi/Htmldom#22]
```php
if (!preg_match("/^[\w-:]+$/", $tag)) {
```
etc fail
See
```
1) Data\Test\TestCase\Lib\GeoImportLibTest::testImportCountiesCH
preg_match(): Compilation failed: invalid range in character class at offset 4
/home/travis/build/dereuromark/cakephp-data/vendor/yangqi/htmldom/src/Yangqi/Htmldom/Htmldom.php:528
/home/travis/build/dereuromark/cakephp-data/vendor/yangqi/htmldom/src/Yangqi/Htmldom/Htmldom.php:332
/home/travis/build/dereuromark/cakephp-data/vendor/yangqi/htmldom/src/Yangqi/Htmldom/Htmldom.php:164
/home/travis/build/dereuromark/cakephp-data/vendor/yangqi/htmldom/src/Yangqi/Htmldom/Htmldom.php:122
```

**Comment by mjarkk** [comment]
Same here with laravel, error:  
```
preg_match(): Compilation failed: invalid range in character class at offset 4
...
at preg_match('/^[\\w-:]+$/', 'html') in Htmldom.php line 528
...
```
Code:
```php
new \Htmldom('<html></html>');
```

**Comment by lloricode** [comment]
same as mine 

php version: 7.3.1

![](https://user-images.githubusercontent.com/8251344/52908455-15ed8a80-32b1-11e9-85ce-0a2bc58d469c.png)

**Comment by xlcrr** [comment]
Works fine for me in test using php 7.1

Fails in production using 7.3

**Comment by mjarkk** [comment]
@xlcrr `preg_match()` works different from php 7.3 and ongoing.
The `-` in that regex needs to be escaped  

Link: https://hackernoon.com/deprecations-and-changes-for-php-7-3-avoid-errors-7a5c4dbeaa8b  
When you search on that page for `preg_match` you'll see why it doesn't work  

I'm not sure if this ever gets fixed because the maker of this project has only 7 contributions last year, I think this project can be seen as dead from 7.3 and up :(

**Comment by mkubenka** [comment]
You can use my fix in #23.

Add package definition to your `composer.json`:

```json
  "repositories": [
    {
      "type": "package",
      "package": {
        "name": "yangqi/Htmldom",
        "version": "master",
        "source": {
          "type": "git",
          "url": "https://github.com/mkubenka/Htmldom.git",
          "reference": "fix/php73"
        }
      }
    }
  ]
```

Change `yangqi/Htmldom` version to `dev-master`:

```json
"yangqi/htmldom": "dev-master",
```

And run:

```
composer update yangqi/htmldom
```

**Comment by lloricode** [comment]
@mkubenka we can wait until release :+1:

**Comment by lloricode** [comment]
@yangqi

**Comment by yangqi** [comment]
Merged #24

**Comment by ysb** [comment]
@yangqi Issue is closed but there is no release. So, composer is loading previous version.
Can you please publish a release?

**Comment by mweghorst** [comment]
@ysb Update your composer.json to include "yangqi/htmldom": "dev-master"
