### ISSUE TITLE
Provider issue when using laravel 6

### ISSUE THREAD

**Issue by lloricode** [yangqi/Htmldom#26]
Hi @yangqi 

https://github.com/yangqi/Htmldom/blob/master/src/Yangqi/Htmldom/HtmldomServiceProvider.php#L21

this this the problem when using this in laravel 6

**Comment by acrossoffwest** [comment]
@lloricode do you know what mean this line? I just created pull request with fix this problem. I'm hoping @yangqi will check it and accept if all okay
