### ISSUE TITLE
Laravel 5 version

### ISSUE THREAD

**Issue by welcoMattic** [yangqi/Htmldom#8]
Hi!

Do you plan a Laravel 5 version of you package? Thanks

**Comment by welcoMattic** [comment]
up

**Comment by yangqi** [comment]
I am starting to look at laravel 5 docs now

**Comment by yangqi** [comment]
updated, it should work with L5 now, let me know if there is an issue.

**Comment by welcoMattic** [comment]
@yangqi Thanks a lot ! I'll test it today
